ProjetSession/Controllers/CommandesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjetSession.Models;

namespace ProjetSession.Controllers
{
    //TODO : 17. Ajouter les autorisations nécessaires pour que:
            // Tout le monde puisse remplir et voir son panier
            // Seul les usagés authentifiés puisse commander et obtenir une confirmation.

    public class CommandesController : Controller // Contrôleur pour les commandes/locations
    {
        IRepFilms FilmsRep;
        IRepLocations LocationsRep;

        /// <summary>
        /// Constructeur du contrôleur CommandesController
        /// </summary>
        /// <param name="repFilms">Référentiel des films</param>
        /// <param name="repLocations">Référentiel des locations</param>
        public CommandesController(IRepFilms repFilms,  IRepLocations repLocations)
        {
            FilmsRep = repFilms;
            LocationsRep = repLocations;
        }

        /// <summary>
        /// Action pour afficher la page de confirmation après une commande/location
        /// </summary>
        /// <returns>La vue de la page de confirmation</returns>
        public IActionResult Confirmation()
        {
            return View();
        }

        private List<Film> GetPanierFromSession()
        {
            List<Film> panier = new List<Film>();
            // TODO : 13. Récupérer le panier de la session.

            return panier; 
        }

        /// <summary>
        /// Action pour afficher le panier actuel
        /// </summary>
        /// <returns>La vue du panier</returns>
        public IActionResult Panier()
        {
            List<Film> panier = GetPanierFromSession();

            return View(panier);
        }

        /// <summary>
        /// Action pour ajouter un film au panier
        /// </summary>
        /// <param name="id">L'identifiant du film à ajouter au panier</param>
        /// <returns>Redirige vers la vue du panier</returns>
        public IActionResult AjouterPanier(int id)
        {
            List<Film> panier = GetPanierFromSession();
            var film = FilmsRep.GetFilm(id);

            panier.Add(film);
            

            //TODO : 12. Sauvegarder le panier dans la session

            return RedirectToAction("Panier");
        }

        /// <summary>
        /// Affiche la page de checkout avec le form à remplir
        /// </summary>
        /// <returns>La vue de la page de checkout</returns>
        public IActionResult Checkout()
        {
            List<Film> panier = GetPanierFromSession();
           
            decimal total = (decimal)(panier?.Sum(s => s.Prix) ?? 0);

            ViewBag.Total = total;

            return View();
        }

        /// <summary>
        /// Action pour valider et effectuer la commande/location
        /// </summary>
        /// <param name="location">Les informations de la location/commande</param>
        /// <returns>Redirige vers la page de confirmation après ajout de la location</returns>
        [HttpPost]
        public IActionResult Checkout(Location location)
        {
            //TODO : 14. Compléter cette méthode pour que la location soit sauvegardée dans la base de données.
            //TODO : 15. Le panier doit aussi être vidé, puis redirger à la confirmation.
            //TODO : 16. Ajouter un commentairs pour expliquer comment la location est sauvegardée.

            return null;
        }
    }
}

ProjetSession/Controllers/HomeController.cs
using ProjetSession.Models;
using Microsoft.AspNetCore.Mvc;

namespace ProjetSession.Controllers
{
    //TODO : 20. Ajouter les autorisations nécessaires pour que :
            //seul l'admin puisse supprimer des films;
            //tout le monde peut afficher la liste et les détails des films.

    public class HomeController : Controller
    {
        IRepFilms FilmsRep;

        /// <summary>
        /// Constructeur du contrôleur Home
        /// </summary>
        /// <param name="repFilms">Référentiel des films</param>
        public HomeController(IRepFilms repFilms)
        {
            this.FilmsRep = repFilms;
        }

        /// <summary>
        /// Affiche la page d'accueil avec la liste des films
        /// </summary>
        /// <returns>La vue de la page d'accueil</returns>
        public IActionResult Index()
        {
            //TODO : 19. Modifier cette méthode pour permettre :
                    // la recherche des films en écrivant une partie de leur nom dans la barre de recherche
            

            return View(FilmsRep.LesFilms());
        }

        /// <summary>
        /// Affiche les détails d'un film
        /// </summary>
        /// <param name="id">L'identifiant du film</param>
        /// <returns>La vue des détails du film</returns>
        public IActionResult Detail(int id)
        {
            var film = FilmsRep.GetFilm(id);
            return View(film);
        }


        /// <summary>
        /// Supprime un film
        /// </summary>
        /// <param name="id">L'identifiant du film à supprimer</param>
        /// <returns>Redirige vers l'index</returns>
        [HttpGet]
        public IActionResult Delete(int id)
        {
            FilmsRep.DeleteFilm(id);
            return RedirectToAction("Index");
        }

    }
}

ProjetSession/Views/Home/Detail.cshtml
@model ProjetSession.Models.Film

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2 text-light">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2 text-light">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class="col-sm-10 text-light">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class="col-sm-2 text-light">
            
        </dt>
    </dl>
    <img src="@Model.ImageUrl" alt="Image à venir..." />
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

ProjetSession/Views/Home/Index.cshtml
@model IEnumerable<ProjetSession.Models.Film>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

@{
    ViewData["Title"] = "Index";
}

<h1>Liste de films à louer</h1>

@* TODO : 18. Ajouter un formulaire de recherche permettant de cherche avec une partie du nom des films. *@

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Nom
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>    
                    <img src="@item.ImageUrl" alt="Image à venir..." style="background-size: cover; height: 13.5rem; width: 9rem; background-repeat: no-repeat;" />
            </td>
               
                <td>
                    @Html.ActionLink("Afficher", "Detail", new {  id=item.Id  }) |
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin")) // admin
                    {
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { onclick = "return confirm('Voulez-vous vraiment supprimer ce film?');" })
                    }    
                </td>
                <td>
                    <a asp-controller="Commandes" asp-action="AjouterPanier" asp-route-id="@item.Id" class="btn btn-success d-flex w-70 btn-last" data-carid="230" data-img="https://www.luxurycarrental.ae/uploads/car/MHnh7yJLUAZKLAyt4qTWLrAy5e8dl5ZqDUH5xcYX.webp">
                        Louer ce film<br>(@DateTime.Now.AddDays(7).Date)<br><span style="font-weight:700;">@item.Prix $</span>
					</a>
                </td>
        </tr>
}
    </tbody>
</table>